SIM ?= verilator
TOPLEVEL_LANG ?= verilog

PWD=$(shell pwd)
VERILOG_SOURCES +=$(PWD)/univ_shift.sv

TOPLEVEL=univ_shift
MODULE=nbit_shiftregister_test


include $(shell cocotb-config --makefiles)/Makefile.sim